site_name: Simple Secrets Manager
repo_name: simple-secrets-manager
repo_url: https://github.com/harttraveller/simple-secrets-manager
edit_uri: edit/main/docs/

nav:
- index.md
- quickstart.md
- tutorial.ipynb
- cli.md
- design.md
- security.md
- features.md
- Changelog:
  - changelog/0.1.1.md
  - changelog/0.1.0.md

theme:
  name: material
  favicon: assets/icon.png
  logo: assets/icon.png
  icon:
    annotation: material/plus-circle
  font:
    text: Inter
    code: Ubuntu Mono
  palette:
    scheme: slate
    primary: black
    accent: orange
  features:
  - content.action.view
  - content.action.edit
  - search.suggest
  - content.code.copy
  - content.code.annotate
  - navigation.tracking
  - navigation.footer
  # - navigation.expand


plugins:
- search
- mkdocs-jupyter
- roamlinks
- git-revision-date-localized:
    enable_creation_date: true

markdown_extensions:
- mkdocs-click
- attr_list
- md_in_html
- admonition
- footnotes
- pymdownx.critic
- pymdownx.caret
- pymdownx.keys
- pymdownx.mark
- pymdownx.tilde
- pymdownx.details
- pymdownx.inlinehilite
- pymdownx.snippets
- pymdownx.superfences
- pymdownx.highlight:
    anchor_linenums: true
    use_pygments: true
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.tabbed:
    alternate_style: true
- pymdownx.highlight:
    anchor_linenums: true
    use_pygments: true
- pymdownx.tasklist:
    custom_checkbox: true
- pymdownx.arithmatex:
    generic: true
- pymdownx.superfences:
    custom_fences:
    - name: mermaid
      class: mermaid
      format: !!python/name:pymdownx.superfences.fence_code_format
